# Use an official Python runtime as a parent image
FROM ubuntu:16.04

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified 
RUN apt-get update && \ 
	apt-get install -y docker && \
	apt-get install -y docker-compose 

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME swarm

# Run app.py when the container launches
CMD ["python", "app.py"]